### ISSUE TITLE
Cannot create new note

### ISSUE THREAD

**Issue by JhonDoe-x** [basham/obsidian-alias-from-heading#15]
When `Ctrl+N` to create new note, there is no response from obsidian. The console error:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'headings')
    at t.eval [as getCache] (plugin:obsidian-alias-from-heading:186:19)
    at t.eval (plugin:obsidian-kanban:67:17806)
    at t.o [as setViewState] (plugin:obsidian-kanban:33:73074)
    at t.<anonymous> (app.js:1:2209264)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at app.js:1:236159
    at new Promise (<anonymous>)
    at v (app.js:1:235904)
    at t.openFile (app.js:1:2208842)
```

**Comment by basham** [comment]
Thanks for posting the issue! It is fixed in v1.1.2.
